### ISSUE TITLE
Limited number of BIASCOR tasks

### ISSUE THREAD

**Issue by geotaylo** [dessn/Pippin#116]
It seems like Pippin only allows a limited number (9) of biascor tasks to be specified in the config. If I add one more, I get this error:

RecursionError: maximum recursion depth exceeded while calling a Python object

I've tried commenting out different tasks to verify it's not an issue with how I'm defining them in my yml file. My current workaround is to comment out the 10th task and then rerun with a different run commented to get them all through.

**Comment by OmegaLambda1998** [comment]
Not a recursive issue, just biascor being a very large object to copy, increased recursion limit: 3db20e63
