### ISSUE TITLE
remove default WFITMUDIF_OPT from 6_BIASCOR stage

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#122]
I just noticed that pippin seems to add WFITMUDIF_OPT in the bbc-input file (6_BIASCOR) even if it is not requested:   $PIPPIN_OUTPUT/KV22_ANA_CALIBSHIFTS/6_BIASCOR/5YR_IaCC_SNN_Baseline/5YR_IaCC_SNN_Baseline.input
Can you remove this default addition, as it just wastes a lot of time and is subject to rare aborts.

**Comment by OmegaLambda1998** [comment]
WFITMUDIF_OPT is no longer default
