### ISSUE TITLE
Feature request: option to use FITOPTs when specifying SIMFILE_BIASCOR

### ISSUE THREAD

**Issue by rebeccachen0** [dessn/Pippin#128]
At the moment the only way to specify your biascor is to give SIMFILE_BIASCOR: [FIT_OUTPUT_BIASCOR], where Pippin automatically selects FITOPT000 from that directory. It would be helpful to have an option to specify a different fitopt from that directory to use as the biascor.

**Comment by OmegaLambda1998** [comment]
Sorry this took so long, I'm testing an implementation now!

**Comment by OmegaLambda1998** [comment]
I have added two keys to the BIASCOR stage:
```
SIMFILE_BIASCOR: [FIT_SIM_1, FIT_SIM_2]
SIMFILE_BIASCOR_FITOPTS: [0, 1] # Use FITOPT000 and FITOPT001 respectively

SIMFILE_CCPRIOR: CCFIT_CCSIM
SIMFILE_CCPRIOR_FITOPTS: 2 # Use FITOPT002
```
