### ISSUE TITLE
Unsure how to include variable (e.g. HOSTGAL_LOGMASS) in LCFIT output FITRES

### ISSUE THREAD

**Issue by geotaylo** [dessn/Pippin#132]
Details here: https://darkenergysurvey.slack.com/archives/CTE4MSWK1/p1683012187281319

**Comment by geotaylo** [comment]
Output directory for Pippin log is $PIPPIN_OUTPUT/GT_MASSSPLIT_R1, specific example is in  $PIPPIN_OUTPUT/GT_MASSSPLIT_R12_LCFIT/LOWZ_HIGHMASS_SIM_SIMLOWZ_HMU/output

**Comment by RickKessler** [comment]
HOST_LOGMASS  and HOST_LOGMASS_ERR are already in the FITRES file, so there is no need to extract the redundant HOSTGAL_LOGMASS.

**Comment by geotaylo** [comment]
Damn, you're right - thanks Rick!
