### ISSUE TITLE
Pippin should record login node in log file.

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#139]
please record login node at top of pippin log in case we need to kill the pippin job later. Note that Midway has 2 login nodes and Perlmutter has ~40 login nodes, so it's easy to lose track of where the pippin background job is lurking.

**Comment by OmegaLambda1998** [comment]
Added: https://github.com/dessn/Pippin/commit/8ead7e3a7aba1e399c1d375a6649e1fd338bfab8
