### ISSUE TITLE
Error couldnot open file. Corrupt input. 

### ISSUE THREAD

**Issue by am610** [dessn/Pippin#148]
in the following folder : 
`PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/6_BIASCOR/BBC_SIMDATA_PHOTOZ/output_ITER1/SCRIPTS_BBCFIT
`
the following error is reported : 
```
- Could not open ascii table file:  
 - '/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/5_MERGE/MERGE_FIT_BIASCOR_PHOTOZ_LSST_BIASCOR_CC/output/PIP_LSST_BIASCOR_LSST_BIASCOR_CC/FITOPT{n:03}.FITRES.gz' 
```
we can find the following : 
```
cd $PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/6_BIASCOR/BBC_SIMDATA_PHOTOZ
 grep ccprior BBC_SIMDATA_PHOTOZ.input
simfile_ccprior=/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/5_MERGE/MERGE_FIT_BIASCOR_PHOTOZ_LSST_BIASCOR_CC/output/PIP_LSST_BIASCOR_LSST_BIASCOR_CC/FITOPT{n:03}.FITRES.gz
```

the file being searched does actually exist : 
`/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/5_MERGE/MERGE_FIT_BIASCOR_PHOTOZ_LSST_BIASCOR_CC/output/PIP_LSST_BIASCOR_LSST_BIASCOR_CC/FITOPT000.FITRES.gz
`

**Comment by RickKessler** [comment]
to clarify the problem, pippin updates the BBC-input file to look for
   FITOPT{n:03}.FITRES
instead of
   FITOPT000.FITRES

**Comment by OmegaLambda1998** [comment]
Missed an f-string during an update, should be fixed now!
Please confirm and close
