### ISSUE TITLE
Pippin job doesnt get in the queue in Perlmutter

### ISSUE THREAD

**Issue by am610** [dessn/Pippin#149]
After launching job, the pippin job doesnt get into the queue, after 1 hour of waiting, there is not jobs in queue. 

`/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU`

**Comment by am610** [comment]
Some additional updates, we found that this happened due to the inability to automatically remove non zipped files in 6_BIASCOR/output/OUTPUT_0*/ folders. 
Upon manually removing the files which are not .gzipped, the process moved fast and jobs appeared in the queue. I don't know what is the cause of this behaviour.

**Comment by OmegaLambda1998** [comment]
Thanks for the extra info, will investigate!

**Comment by OmegaLambda1998** [comment]
What do you mean by automatically remove? What part of the process should be removing these folders?
