### ISSUE TITLE
Permission issues

### ISSUE THREAD

**Issue by am610** [dessn/Pippin#150]
This is not a major issue, but nuisance nevertheless. Can this ownership error be averted ? 

```
Chown error: /pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/2_LCFIT/FIT_DC2LOWZ_BIASCOR_DC2LOWZ_BIASCOR
Traceback (most recent call last):
  File "/global/u1/a/ayanmitr/soft/Pippin/pippin/config.py", line 214, in chown_dir
    os.chown(directory, -1, group_id)
PermissionError: [Errno 1] Operation not permitted: '/pscratch/sd/d/desctd/PIPPIN_OUTPUT/LSST_COMBINED_CC_GPU/2_LCFIT/FIT_DC2LOWZ_BIASCOR_DC2LOWZ_BIASCOR'


```

**Comment by OmegaLambda1998** [comment]
What is the context for this error? Did you run a job that originally belonged to someone else?

**Comment by am610** [comment]
Yes, so Rick started this job, he ran till stage 2. I re-launched the job, and now it has progressed successfully till stage 6, (where there are different set of errors, which I have posted as a separate issue) but in between keeps throwing this permission errors.

**Comment by OmegaLambda1998** [comment]
Unfortunately there's not much that can be done about that (see https://superuser.com/questions/697608/chown-operation-not-permitted)

Your best choice if you wanted to use Rick's results is to make your own pippin job and just use Rick's output as an external result (i.e with `EXTERNAL: /path/to/ricks/results`)

If you wanted to keep the name of the Pippin file, just rename the directory containing Rick's results.
