### ISSUE TITLE
git pull permission denied on Perlmutter

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#154]
<img width="918" alt="pippin-permission" src="https://github.com/dessn/Pippin/assets/24592476/ba4df76d-0745-41f1-a613-8f75e89969c3">

**Comment by OmegaLambda1998** [comment]
I've added you as a collaborator. I may need to change the rw permissions of the directory on perlmutter but can you give a pull a shot?

**Comment by RickKessler** [comment]
git pull
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
