### ISSUE TITLE
Pippin hangs on lcfit failures

### ISSUE THREAD

**Issue by darcykenworthy** [dessn/Pippin#155]
Pippin appears to hang when I give some incorrect inputs in the nml file for light-curve fits.

Input file that reproduces issue:

/project2/rkessler/SURVEYS/DES/USERS/dkenworthy/pippinlearning/darcytesting.yml

**Comment by OmegaLambda1998** [comment]
Typically Pippin looks for an ALL.DONE file which is written by SNANA to know whether the job succeeded or failed. For some reason SNANA didn't write that file this time...
I would suggest putting an issue in with SNANA to try and see why there was no fail file written.
