### ISSUE TITLE
Incorrect behavior when using prior

### ISSUE THREAD

**Issue by darcykenworthy** [dessn/Pippin#156]
When using the half-gaussian prior, I noticed that there were too few points appearing in the flat region of the prior, ostensibly the most likely region.

Ideally, including a simple Gaussian prior as an option would be the most desired solution.

Input file was /project2/rkessler/SURVEYS/DES/USERS/dkenworthy/ztf_lcfitting/snfit_multi.nml

**Comment by OmegaLambda1998** [comment]
Hi Darcy, this is more an SNANA issue than a Pippin issue, consider posting an issue at https://github.com/RickKessler/SNANA/issues?

**Comment by darcykenworthy** [comment]
Oh, whoops! Put this here by total accident.D’Arcy Sent from my iPhoneOn Feb 19, 2024, at 11:42 PM, Patrick Armstrong ***@***.***> wrote:﻿
Hi Darcy, this is more an SNANA issue than a Pippin issue, consider posting an issue at https://github.com/RickKessler/SNANA/issues?
