### ISSUE TITLE
check sim INCLUDE files for GENMODEL key

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#157]
Current pippin code requires GENMODEL key in the primary sim-input file, so it fails if GENMODEL is defined in an INCLUDE file.
Here is example code (on RCC) to search keys in primary sim-input and its include files:
$SNANA_DEBUG/get_simInput_key_values/test_get_simInput.py

Note that get_simInput_key_values() returns a list for each key since some keys are allowed to be defined multiple times. Please call this new get_simInput_key_values utility from pippin (either import from $SNANA_DIR/util, or install the method inside pippin)

**Comment by OmegaLambda1998** [comment]
This has been added. However, I'm going to hard code this function into Pippin rather than use the SNANA version so that github tests work

**Comment by OmegaLambda1998** [comment]
Tests fixed
