### ISSUE TITLE
separate log file for each heat map task

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#158]
In a typical heat map task for training, there are many sbatch files, e.g,
ls create_heatmaps__*.sh
create_heatmaps__0.sh   create_heatmaps__2.sh  create_heatmaps__5.sh  create_heatmaps__8.sh
create_heatmaps__10.sh  create_heatmaps__3.sh  create_heatmaps__6.sh  create_heatmaps__9.sh
create_heatmaps__1.sh   create_heatmaps__4.sh  create_heatmaps__7.sh

A problem is that every .sh file points to the same log file, making it difficult to parse when there are problems. It would be easier to diagnose the task if each create_heatmaps__[n].sh file produced a log file with same base name;
create_heatmaps__[n].log

**Comment by OmegaLambda1998** [comment]
@helenqu is this something you can implement?

**Comment by RickKessler** [comment]
I implemented this a while ago in the refactored code, so may be a while before it is pushed to GitHub,
