### ISSUE TITLE
Analysis run crashes on calling salt2mu.exe in 6_Biascor stage 'Could not open ascii table file'

### ISSUE THREAD

**Issue by paulshah** [dessn/Pippin#166]
Input files are in $DES_USERS/shahpa/ and are PS_biascor.yml, PS_sim_nominal.yml, PS_analysis.yml

Output is in $PIPPIN_OUTPUT/PS_ANALYSIS

PS_biascor and PS_sim_nominal complete, PS_analysis runs up to stage 6_BIASCOR when it crashes with log excerpt :

[   DEBUG |           biascor.py:450]   Running command: submit_batch_jobs.sh NOMINALSIM.input
...
[  ERROR |       task.py:322]  Found error in file /scratch/midway2/rkessler/PIPPIN_OUTPUT/PS_ANALYSIS/6_BIASCOR/NOMINALSIM/OUTPUT_BBCFIT-0001_FITOPT000_MUOPT008.LOG, excerpt below
[  ERROR |       task.py:324]  Excerpt:   FATAL ERROR ABORT called by SNTABLE_NEVT_TEXT
[  ERROR |       task.py:324]  Excerpt:    Could not open ascii table file:
[  ERROR |       task.py:324]  Excerpt:    ‘../OUTPUT_BBCFIT-0001/INPUT_FITOPT000.FITRES’
[  ERROR |       task.py:324]  Excerpt:

According to the logs this crash is on calling : 

SALT2mu.exe NOMINALSIM.input prefix=OUTPUT_BBCFIT-0001_FITOPT000_MUOPT008 datafile=../OUTPUT_BBCFIT-0001/INPUT_FITOPT000.FITRES write_yaml=1 varname_pIa=PROB_SCONE chi2max=10000000

If I go to the directory $PIPPIN_OUTPUT/PS_ANALYSIS/6_BIASCOR/NOMINALSIM/output/SCRIPTS_BBCFIT, I can run that same command with no error (but only from that directory given the relative datafile).

**Comment by OmegaLambda1998** [comment]
The base bbc file you used (`$SNDATA_ROOT/sample_input_files/DES-SN5YR/base_files/bbc/BBC_des5yr.input`) includes the following line:

WFITMUDIF_OPT: -speed_flag_chi2 0 -wsteps 801 -ommin 0.0 -ommax 1 -omsteps 501 -hmin 40 -hmax 100 -hsteps 501 -ompri 0.315 -dompri 10

It looks like the -hmin and -hmax aren't valid options (see for example `NOMINAL/wfit_PIP_PS_SIM_NOMINAL_DATADESSIM_LENS-0001_FITOPT000_MUOPT002.LOG`). Not sure why that is, have submitted an issue  to SNANA (https://github.com/RickKessler/SNANA/issues/1339), but for the moment just overwrite those options by adding:

`WFITMUDIF_OPT: -speed_flag_chi2 0 -wsteps 801 -ommin 0.0 -ommax 1 -omsteps 501 -hsteps 501 -ompri 0.315 -dompri 10` to your BIASCOR config (at the same level as `DATA`)
