### ISSUE TITLE
copy new COV-stat file from BBC to CosmoMC

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#23]
BBC/SALT2mu now writes out the full Nzbin x Nzbin COV-stat matrix to [prefix].COV. Output from submit_batch_jobs will include [prefix].FITRES, [prefix].M0DIF, and [prefix].COV. While we prepare a new BBC interface for CosmoMC, pippin needs to copy this COV_STAT file to the same place as the COV_SYST file.

**Comment by OmegaLambda1998** [comment]
Is this still an issue?

**Comment by OmegaLambda1998** [comment]
Closed for the moment
