### ISSUE TITLE
Need Pippin input to pass OPT_SNCID_LIST to the LC fit config

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#28]
To use same events in LC fit systematics,
CONFIG:
   BATCH_INFO: bla bla bla
   BATCH_MEM: bla
   OPT_SNCID_LIST: 1   # < === new key for submit_batch_jobs

**Comment by djbrout** [comment]
did you try just adding OPT_SNCID_LIST: 1 in the OPTS: section of the lcfitting stage? it should just work as far as i can tell.

**Comment by RickKessler** [comment]
I have not tried OPTS section ...but I thought there is already a key to specify common set of SN, so why not automatically set OPT_SNCID_LIST ?

**Comment by djbrout** [comment]
because that key is set in the biascor stage and so the LCFIT stage doesnt
know anything about that key.

**Comment by OmegaLambda1998** [comment]
@RickKessler, @djbrout Is this still an issue or has this been resolved?

**Comment by OmegaLambda1998** [comment]
Resolved
