### ISSUE TITLE
Allow BBC: or BIASCOR: in Pippin input file

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#57]
6_BIASCOR is a rather misleading name. Please allow alternate 6_BBC

**Comment by OmegaLambda1998** [comment]
Do you mean allow the directory to be name 6_BIASCOR or 6_BBC, or do you mean in the input file itself being able to write
```
BBC:
    blah
    blah
```

**Comment by RickKessler** [comment]
BBC:
   bla
   bla

which results in 
6_BBC output directory
