### ISSUE TITLE
do not remove simfile_biascor without alternative

### ISSUE THREAD

**Issue by RickKessler** [dessn/Pippin#75]
We would like to specify   simfile_biascor=<long_list> in the BBC input file and NOT specify SIMFILE_BIASCOR in pippin, but pippin removes simfile_biascor key. We request a fix so that simfile_biascor key is left as is unless there is a specific override option. Or, there could be an explicit user request such as
   SIMFILE_BIASCOR [ 'simfile_biascor' ]
which explicitly instructs Pippin to leave simfile_biascor alone.

**Comment by OmegaLambda1998** [comment]
Can you go to `/project2/rkessler/SURVEYS/DES/USERS/parmstrong/dev/pippin-pa` and run `./pippin.sh -v path/to/your/input.yml` to test whether this is still an issue?

**Comment by OmegaLambda1998** [comment]
d3b6241 should fix this. If not, please reopen this issue
