### ISSUE TITLE
Request - override key for EXTERNAL_DIR in LCFIT 

### ISSUE THREAD

**Issue by bap37** [dessn/Pippin#85]
Morning - 

After some thought and a bit of discussion, I think an override key for importing already-fit files would go a long way.

So to lay out my thoughts - pippin already has a feature to import external sims for 2_LCFIT and is _supposed_ to be able to recognise when to re-fit them and when to import the existing files without refitting. Unfortunately this is a bit finnicky and often results in pippin refitting due to... arcane reasons, likely some odd hash mismatch that's super difficult to identify. 

To that end, a flag to tell pippin "import this external directory as-is, don't try to hash check / refit" would be immensely helpful. Oftentimes these external sims that are imported are very large biascor files that take a significant time to refit, causing slowdowns. 

Thanks!

**Comment by OmegaLambda1998** [comment]
This ended up being due to the fact the the `EXTERNAL_DIRS` had a different task name to the `LCFIT` task. This is resolved by adding the `EXTERNAL_MAP` key, as per #86
