### ISSUE TITLE
sn_cmb_omw tasks not running in CosmoFit 

### ISSUE THREAD

**Issue by geotaylo** [dessn/Pippin#93]
I'm getting a weird cosmomc error that I'm not sure how to resolve. It'll run my sn_omw tasks no problem, but does not like the sn_cmb_omw tasks - I get this error message in $PIPPIN_OUTPUT/GT_SALT23_FRAG_3YRTEST/8_COSMOFIT/COSMOMC/COSMOMC_SN_CMB_OMW_ALL_3YR_322/output.log :

<img width="730" alt="image" src="https://user-images.githubusercontent.com/24376501/176720208-4d39ae83-bfe4-41a6-93ad-4595eb6536e7.png">

I believe that we've changed to v04 of cosmoMC on Midway now, but I don't know how to fix it myself. Any ideas?

yml is $PIPPIN_OUTPUT/GT_SALT23_FRAG_3YRTEST/gt_salt23_frag_3yrtest.yml

**Comment by OmegaLambda1998** [comment]
It looks like the `common.ini` file referenced by `cmb_omw.ini` still sets it's `DATA_DIR` to v03. I don't currently have write access to cosmomc, but I will try to get that resolved

**Comment by OmegaLambda1998** [comment]
Seems like other cosmomc errors abound, but this particular one is resolved
